### PR TITLE
Update bower.json: main should not be the minified version

### PR DESCRIPTION
**Pull request by Alban34**
The main file should not be the minified one: it's up to developers to minify or not their external libraries

### CODE REVIEW

**Comment by Teun** [comment]
Thanks for your contribution. I am not very fluent in using bower. Could you point me to some form of bower docs that indicate that the main file should not be minified?

**Comment by Alban34** [comment]
Hi, I'm not sure there is a bower doc regarding this (I never saw it to be
honest) but your project is the only one I use that provide as "main" the
minified file (and I'm using quite a lot of projects: angular.js,
handsontable, many angular.js plugins). So I guess this is more a best
practice: when you develop you include the full source and once you build
you production solution, you minify all external libs with yours. Does it
make sense?

**Comment by Teun** [comment]
OK, I see. I'll have a look at your PR and merge it if I understand what it does.

**Comment by Teun** [comment]
Thank you.

**Comment by Alban34** [comment]
Thanks! And could you also push the latest release build on github as de
cannot pull it with bower until it's done.

Le 13 août 2016 8:46 PM, "Teun Duynstee" <notifications@github.com> a
écrit :

**Comment by Teun** [comment]
Actually, I think bower currently points not even to my original location, but to the fork at https://github.com/shaununderwood/thenBy.js. Not sure what should happen to make this all OK.

**Pull request merged**
