### PR TITLE
build clean

### PR DESCRIPTION
**Pull request by mh-cbon**

### CODE REVIEW

**Comment by mh-cbon** [comment]
@Teun ?

**Comment by Teun** [comment]
Yes, I will merge this soon, but want to have a good look first. Been a bit busy lately.

**Comment by Teun** [comment]
I've merged your improvements. One more question: the output for minification is now much larger, wrapping the code in an AMD compatible wrapper. I would also like to still have a version that is as small as possible and can be linked into an html page directly using a script tag. Of course I can add another task (minify-classic) doing just that, but maybe we can have the minify task output both variants?

**Comment by mh-cbon** [comment]
The tests [here](https://github.com/Teun/thenBy.js/blob/master/tests/index.html#L15) shows an intergration without any amd. The umd integrated binds window too. Are we looking at the same numbers (600b vs 700b) when you say its much larger ?

**Comment by Teun** [comment]
:) Sorry for that wording. I guess I'm unreasonably attached to keep that size small. This library started as a micro-library of about 150 characters. I have been adding features, but always tried to keep it really lightweight. It has now gone from 524 to 673 with no real functionality. Which is fine if you want to use it as an AMD module, but a pity if you want to just paste it in your own library or web page. So I would like to have thenBy.min.js as it is now, but create another version (thenBy.raw.min.js or something like that).

**Comment by mh-cbon** [comment]
Hi, just for the records,

```sh
[mh-cbon@pc15-home thenBy.js] $ gzip -c thenBy.min.js | wc -c
421
[mh-cbon@pc15-home thenBy.js] $ gzip -c thenBy.js | wc -c
941
```
In this attempt to save every bytes, why not reduce the banner to its bare minimum ?

I d suggest to refactor the original code so its directly a node module, thus get ride of the node task, and i guess a new task is needed for what you want.  I m unsure that gulp can do both min and raw.min within the same task.

**Comment by mh-cbon** [comment]
@Teun  what do you think ?

**Comment by Teun** [comment]
Yeah, I guess you have a point. I hope to pick this up soon, but it doesn't seem urgent. All versions are now modules and can be used from npm or bower. Will look at the best way to build and minify later. Thanks for your feedback.

**Comment by mh-cbon** [comment]
Hi, i m waiting for a publish on npm, in fact. Let me know. Thanks.

**Comment by Teun** [comment]
Oops, published as 1.2.3

**Pull request merged**
