### PR TITLE
Added the option to ignore case for property names and unary functions.

### PR DESCRIPTION
**Pull request by Foxhoundn**
A little enhancement to make ignoring case when sorting easier. By default the sort() function sorts data first by upper case letters, which is not desired most of the time (at least in our case it wasn't). This commit enables ignoring case, but **only for property names and unary functions**! Normal functions have to handle the ".toLowerCase()" on their own.

Added 5 tests to make sure this works as expected.

To ignore a case, simply pass a third parameter to the firstBy or thenBy functions.

### CODE REVIEW

**Comment by Teun** [comment]
Thanks for your pull request. You mention unit tests you added, but I don't see them. Maybe you forgot to push? I'm considering changing you implementation a bit, so it would definitely help to have your tests.

**Comment by Foxhoundn** [comment]
Hey, yeah. Pushed the tests as well.

**Comment by Teun** [comment]
Hi, I have refactored your suggestion a bit to make it smaller and maybe also more future-proof. Can you have a look and share your ideas about the current state? https://github.com/Teun/thenBy.js/tree/Foxhoundn-master
It now allows for 

    firstBy("country", {ignoreCase:true, direction:-1});

It also supports ignoreCase on arbitrary unary functions. I am thinking of changing the interface to something like:

    firstBy("country", {compare:firstby.IGNORE_CASE, direction:-1});

**Comment by Foxhoundn** [comment]
Hey, looks good, but I think the latter example has too much confusing boilerplate.

**Comment by Teun** [comment]
Merged, version bumped to 1.2.0. Thanks for the idea and implementation.

**Pull request merged**
